---
title: "Chapter 11"
author: "Mike Campbell"
date: "23/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Regression for Chapter 11
Height<-c(110,116,124,129,131,138, 142,150,153,155,156,159,164,168,174)
Dead<-c(44,31,43,45,56,79,57,56,58,92,78,64,88,112,101)
#scatter plot Fig 11.1
plot(Height, Dead, ylab="Deadspace (ml)", xlab="Height (cm)")
cor(Height, Dead)
cor( Height, Dead, method="spearman")
cor.test(Height, Dead)
cor.test(Height, Dead, method="spearman", exact=NULL)
mod<-lm(Dead~Height)
summary(mod)
confint(mod)
#Scatter plot fig 11.2
abline(mod)
summary(mod)
# plotting residuals against fitted values
plot(mod$fitted,mod$resid, ylab="Residuals", xlab="Fitted values")
# centering the x and y variables
dm<-Dead-mean(Dead)
hm<-Height-mean(Height)
mod1<-lm(dm~hm)
summary(mod1)
```
Regression instead of a t-test from data in Table 9.1

```{r}
# Using regression to do the t-test on the data in Table 9.1
# Need to arrange all data in columns, and gp =1 for y's and 0 for x's 

# x are the data for treatment A
x<-c(44,51,52,55,60,62,66,68,69,71,71,76,82,91,108)

#y are the data for treatment B
y<-c(52,64,68,74,79,83,84,88,95,97,101,116)


ycom<-c(x,y)
gp<-rep(c(0,1),c(15,12))
mod<-lm(ycom~gp)
summary(mod)
confint(mod)

```
The following R code gives the results of the exercise 11.2
# Exercises in Chapter 11
```{r}
y<- c(21,12, 30, 8, 10, 26, 42, 31, 21, 15, 19, 6, 18, 12, 23, 34)
x<- c(6.8, 10.3, 1.7, 14.2, 8.8, 5.8, 2.1, 3.3, 4.3, 9.0, 3.2, 12.7, 8.2, 7.0, 5.1, 4.1)
plot(x,y)
cor(y,x)
cor(y,x, method="spearman")
mod<-lm(y~x)
summary(mod)
confint(mod)
#change point 12- save old values
x1<-x[12]
y1<-y[12]
x[12]<-22.7
y[12]<-6
cor(y,x)
cor(y,x, method="spearman")
mod<-lm(y~x)
summary(mod)
#change point 6, restore point 12
x[12]<-x1
y[12]<-y1
x[6]<-10
y[6]<-5.8
cor(y,x)
cor(y,x, method="spearman")
mod<-lm(y~x)
summary(mod)


```


